### ISSUE TITLE
I want to know the image size this model was trained on for easier conversion to ONNX.

### ISSUE THREAD

**Issue by m1655451660** [Leaf48/YOLO-Models-For-ApexLegends#2]

**Comment by Leaf48** [comment]
No. I set this image size to lighten processing speed.

**Comment by m1655451660** [comment]
What size images was this model trained on, such as 640*640 or 416*416?

**Comment by m1655451660** [comment]
What size images was this model trained on, such as 640 x 640 or 416 x 416?

**Comment by Leaf48** [comment]
I don't really remember probably it is 160, 320 or 640.
